spring.application.name=mmorpg

# ============================================
# CONEXIÓN A MONGODB (LOCAL - SIN ARCHIVO HOSTS)
# ============================================
# Usamos localhost y directConnection=true para ignorar los nombres internos de Docker
spring.data.mongodb.uri=mongodb://localhost:27017/db_laboratorio?directConnection=true

# Activar logs de Mongo para depuración
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# ============================================
# JWT Y SEGURIDAD
# ============================================
jwt.secret=MMORPG_grupo3_llavesupersecreta_1234124124u1u2i2387472