spring.application.name=mmorpg
server.port=8080
spring.data.mongodb.uri=mongodb://mongo-primary:27017,mongo-secondary:27018/mmorpg_db?replicaSet=rs0
jwt.secret=MMORPG_grupo3_llavesupersecreta_1234124124u1u2i2387472
