spring.application.name=mmorpg
server.port=8080

# ============================================
# CONEXION A MONGODB (DOCKER REPLICA SET)
# ============================================
spring.data.mongodb.uri=mongodb://mongo-primary:27017,mongo-secondary:27017/db_laboratorio?replicaSet=rs0

# Activar logs de Mongo para depuracion
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# ============================================
# JWT Y SEGURIDAD
# ============================================
jwt.secret=MMORPG_grupo3_llavesupersecreta_1234124124u1u2i2387472

# LINEA CLAVE PARA LOS INDICES:
spring.data.mongodb.auto-index-creation=true
