spring.application.name=mmorpg

# CONFIGURACION DE CONEXION (JDBC LOCAL)
spring.datasource.url=jdbc:postgresql://localhost:5435/db_laboratorio
spring.datasource.username= admin_raid
spring.datasource.password= superpassword123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# INICIALIZACION DE BASE DE DATOS
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.separator=//
# JWT Y SEGURIDAD
jwt.secret=MMORPG_grupo3_llavesupersecreta_1234124124u1u2i2387472

# RESTRICCIONES (CERO ORM)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
