spring.application.name=geo

#Configuracion base de datos inicial
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/backend-control2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:adminControl}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Elpro123#}

# Configuración de Hibernate
# 'update' creará las tablas automáticamente si aún no existen
spring.jpa.hibernate.ddl-auto=create

# Esperar a que Hibernate cree las tablas (update/create) antes de correr archivos .sql
spring.jpa.defer-datasource-initialization=true

# Permite ver las consultas SQL que hace Spring en la consola (muy útil para debug)
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A47
jwt.expiration=86400000
