spring.application.name=geo

#Configuracion base de datos inicial
spring.datasource.url=jdbc:postgresql://localhost:5432/backend-control2
spring.datasource.username=adminControl
spring.datasource.password=Elpro123#

Configuración de Hibernate
# 'update' creará las tablas automáticamente si aún no existen
spring.jpa.hibernate.ddl-auto=update

# Esperar a que Hibernate cree las tablas (update/create) antes de correr archivos .sql
spring.jpa.defer-datasource-initialization=true

# Permite ver las consultas SQL que hace Spring en la consola (muy útil para debug)
spring.jpa.show-sql=true
