-- Creamos las tablas
-- Comuna: id_comuna(PK), Nombre_comuna
CREATE TABLE Comuna (
    Id_Comuna INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Comuna VARCHAR(100) NOT NULL
);

-- Rol_Empleado: id_rol(PK), nombre_rol
CREATE TABLE Rol_Empleado (
    Id_Rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Rol VARCHAR(50) NOT NULL
);

-- Categoria_producto: id_categoria_producto (PK), Nombre_categoria
CREATE TABLE Categoria_Producto (
    Id_Categoria_Prod INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Categoria VARCHAR(50) NOT NULL
);

-- Categoria_servicio: id_Categoria_serv(PK), nombre_catgoria
CREATE TABLE Categoria_Servicio (
    Id_Categoria_Serv INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Categoria VARCHAR(50) NOT NULL
);

-- Peluqueria: Id_Peluqueria (PK), id_Comuna (FK), nombre, Calle, Numero
CREATE TABLE Peluqueria (
    Id_Peluqueria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Comuna INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Calle VARCHAR(150) NOT NULL,
    Numero VARCHAR(20) NOT NULL,
    FOREIGN KEY (Id_Comuna) REFERENCES Comuna(Id_Comuna)
);

-- Cliente: Id_Cliente (PK), Rut_Cliente, Nombres, Apellido_paterno, Apellido_materno, Correo_Cliente, Fecha_Nacimiento, id_Comuna(FK), Genero
CREATE TABLE Cliente (
    Id_Cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Rut_Cliente VARCHAR(20) UNIQUE NOT NULL,
    Nombres VARCHAR(100) NOT NULL,
    Apellido_Paterno VARCHAR(100) NOT NULL,
    Apellido_Materno VARCHAR(100),
    Correo_Cliente VARCHAR(150) UNIQUE NOT NULL,
    Fecha_Nac DATE,
    Genero VARCHAR(20),
    Id_Comuna INT,
    FOREIGN KEY (Id_Comuna) REFERENCES Comuna(Id_Comuna)
);

-- Empleado: Id_Empleado (PK), Rut_Empleado (UNIQUE), Nombres, Apellidos, id_Rol(FK), Id_Peluqueria (FK)
CREATE TABLE Empleado (
    Id_Empleado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Rut_Empleado VARCHAR(12) UNIQUE NOT NULL,
    Nombres VARCHAR(100) NOT NULL,
    Apellidos VARCHAR(100) NOT NULL,
    Id_Rol INT NOT NULL,
    Id_Peluqueria INT NOT NULL,
    FOREIGN KEY (Id_Rol) REFERENCES Rol_Empleado(Id_Rol),
    FOREIGN KEY (Id_Peluqueria) REFERENCES Peluqueria(Id_Peluqueria)
);

-- Producto: Id_Producto (PK), Nombre_Producto, Precio_Producto, Stock,  Id_Categoria_Prod(FK)
CREATE TABLE Producto (
    Id_Producto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Producto VARCHAR(150) NOT NULL,
    Precio_Producto INT NOT NULL,
    Stock INT NOT NULL,
    Id_Categoria_Prod INT NOT NULL,
    FOREIGN KEY (Id_Categoria_Prod) REFERENCES Categoria_Producto(Id_Categoria_Prod)
);

-- Servicio: Id_Servicio (PK), Nombre_Servicio, Precio_Actual, id_Categoria_servicio(FK)
CREATE TABLE Servicio (
    Id_Servicio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(150) NOT NULL,
    Precio INT NOT NULL,
    Id_Categoria_Serv INT NOT NULL,
    FOREIGN KEY (Id_Categoria_Serv) REFERENCES Categoria_Servicio(Id_Categoria_Serv)
);

-- Cliente_Peluqueria: (Id_Cliente(FK) y id_peluqueria(FK))(PK)
CREATE TABLE Clientes_Peluqueria (
    Id_Cliente INT NOT NULL,
    Id_Peluqueria INT NOT NULL,
    PRIMARY KEY (Id_Cliente, Id_Peluqueria),
    FOREIGN KEY (Id_Cliente) REFERENCES Cliente(Id_Cliente),
    FOREIGN KEY (Id_Peluqueria) REFERENCES Peluqueria(Id_Peluqueria)
);

-- Sueldo: Id_Sueldo (PK), Id_Empleado (FK), fecha, Monto, Estado
CREATE TABLE Sueldo (
    Id_Sueldo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Empleado INT NOT NULL,
    Fecha DATE NOT NULL,
    Monto INT NOT NULL,
    Estado VARCHAR(50) NOT NULL,
    FOREIGN KEY (Id_Empleado) REFERENCES Empleado(Id_Empleado)
);

 -- Horario: Id_Horario (PK), Dia_Semana, Hora_Inicio, Hora_Fin
CREATE TABLE Horario (
    Id_Horario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Dia_Semana INT NOT NULL, 
    Hora_Inicio TIME NOT NULL,
    Hora_Fin TIME NOT NULL
);

-- Cita: Id_Cita (PK), Id_Cliente (FK), Id_Peluqueria (FK), Id_Empleado (FK), id_Horario(FK) ,Estado_Cita, Fecha_cita
CREATE TABLE Citas (
    Id_Cita INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Peluqueria INT NOT NULL,
    Id_Cliente INT NOT NULL,
    Id_Empleado INT NOT NULL,
    Id_Horario INT NOT NULL,
    Estado_Cita VARCHAR(50) NOT NULL,
    Fecha_Cita DATE NOT NULL, 
    FOREIGN KEY (Id_Peluqueria) REFERENCES Peluqueria(Id_Peluqueria),
    FOREIGN KEY (Id_Cliente) REFERENCES Cliente(Id_Cliente),
    FOREIGN KEY (Id_Empleado) REFERENCES Empleado(Id_Empleado),
    FOREIGN KEY (Id_Horario) REFERENCES Horario(Id_Horario)
);

-- Pago: Id_Pago (PK), Id_Cita (FK), Fecha_Pago, Monto_Total, Medio_Pago, Estado_Pago
CREATE TABLE Pago (
    Id_Pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Cita INT NOT NULL,
    Fecha_Pago DATE NOT NULL,
    Monto_Total INT NOT NULL, 
    Medio_de_pago VARCHAR(50) NOT NULL,
    Estado_pago VARCHAR(50) NOT NULL,
    Tipo_Comprobante VARCHAR(50) NOT NULL,
    FOREIGN KEY (Id_Cita) REFERENCES Citas(Id_Cita)
);

-- Detalle_Cita: Id_Detalle (PK), Id_Cita (FK), Id_Producto (FK), Id_Servicio (FK), Cantidad, Precio_Unitario, Subtotal
CREATE TABLE Detalle_Cita (
    Id_Detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Cita INT NOT NULL,
    Id_Producto INT NULL, 
    Id_Servicio INT NULL, 
    Precio_Unitario INT NOT NULL,
    Subtotal INT NOT NULL,
    Cantidad INT NOT NULL DEFAULT 1,
    FOREIGN KEY (Id_Cita) REFERENCES Citas(Id_Cita),
    FOREIGN KEY (Id_Producto) REFERENCES Producto(Id_Producto),
    FOREIGN KEY (Id_Servicio) REFERENCES Servicio(Id_Servicio)
);