spring.application.name=mmorpg

# ============================================
# CONEXION A BASE DE DATOS (PostGIS + Postgres)
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5435/db_laboratorio
spring.datasource.username=admin_raid
spring.datasource.password=superpassword123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# ============================================
# JPA / HIBERNATE
# ============================================
# Hibernate crea/actualiza las tablas automáticamente desde las Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.spatial.use_native=true

# ============================================
# INICIALIZACION DE DATOS (schema.sql)
# ============================================
# Se ejecuta DESPUES de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.separator=//

# ============================================
# JWT Y SEGURIDAD
# ============================================
jwt.secret=MMORPG_grupo3_llavesupersecreta_1234124124u1u2i2387472
